### ISSUE TITLE
Cumulative Profit chart displays incorrect value

### ISSUE THREAD

**Issue by t3ch9** [froggleston/freqtrade-frogtrade9000#13]
The value displayed in the Trades Summary (left side) is different than value displayed in Cumulative Profit (right side).

For example, Trades Summary displays total of 28.49, but Cumulative Profit chart incorrectly displays 24.00

**Comment by t3ch9** [comment]
Checked the values from rest_client profit which confirms that Trades Summary values are correct. Since posting the original comment in this thread, more trades have closed in profit but the Cumulative Profit chart has not updated and displays incorrect value.

**Comment by froggleston** [comment]
Yeah the chart is inaccurate - I've wanted to fix this for a while but never got round to it
